# Generated by Django 6.0 on 2026-01-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(db_index=True, max_length=100)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('p_throws', models.CharField(blank=True, max_length=10, null=True)),
                ('pitch_type', models.CharField(blank=True, max_length=10, null=True)),
                ('release_speed', models.FloatField(blank=True, null=True)),
                ('release_pos_x', models.FloatField(blank=True, null=True)),
                ('release_pos_y', models.FloatField(blank=True, null=True)),
                ('release_pos_z', models.FloatField(blank=True, null=True)),
                ('vx0', models.FloatField(blank=True, null=True)),
                ('vy0', models.FloatField(blank=True, null=True)),
                ('vz0', models.FloatField(blank=True, null=True)),
                ('ax', models.FloatField(blank=True, null=True)),
                ('ay', models.FloatField(blank=True, null=True)),
                ('az', models.FloatField(blank=True, null=True)),
                ('sz_top', models.FloatField(blank=True, null=True)),
                ('sz_bot', models.FloatField(blank=True, null=True)),
                ('pfx_x', models.FloatField(blank=True, null=True)),
                ('pfx_z', models.FloatField(blank=True, null=True)),
                ('release_spin_rate', models.FloatField(blank=True, null=True)),
                ('plate_x', models.FloatField(blank=True, null=True)),
                ('plate_z', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
