# Generated by Django 6.0 on 2026-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MlbPlayerCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('player_type', models.CharField(choices=[('batter', '타자'), ('pitcher', '투수')], default='batter', max_length=10)),
                ('salary', models.BigIntegerField(default=0)),
                ('war', models.FloatField(default=0.0)),
                ('dollars', models.BigIntegerField(default=0)),
                ('surplus_value', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'player_type'], name='analysis_ml_year_22b711_idx'), models.Index(fields=['year', 'name'], name='analysis_ml_year_b79d2f_idx')],
                'unique_together': {('year', 'name', 'player_type')},
            },
        ),
    ]
